### PR TITLE
Factor out functionality to Axelrod

### PR DESCRIPTION
**Pull request by marcharper**
This PR removed the functionality transferred to Axelrod and updates the rest of the library to continue functioning (see the associated [PR](https://github.com/Axelrod-Python/Axelrod/pull/1256)). The tests will fail until Axelrod is updated and we should probably bump both versions accordingly.

### CODE REVIEW

**Comment by marcharper** [comment]
@drvinceknight All the tests pass locally for me but they won't pass here until we push a new release of Axelrod. It may also be necessary to bump the minimum version in requirements.txt.

**Comment by drvinceknight** [comment]
Of course! Sorry, was thinking I need to do another Axelrod release, will do my best to do that today/tomorrow. :+1:

**Comment by drvinceknight** [comment]
I've released 4.7.0 @marcharper :+1: see https://pypi.org/project/Axelrod/

**Comment by marcharper** [comment]
Thanks! Tests are all passing now.

**Comment by drvinceknight** [comment]
Thanks @marcharper :+1:

**Pull request merged**
