### PR TITLE
Fixed Swap Nodes in mutate_rows per issue #41

### PR DESCRIPTION
**Pull request by gaffney2010**
Swapped based on state, row[0], then sorted.  As per our conversation in issue #41 thread.

### CODE REVIEW

**Comment by gaffney2010** [comment]
Is this telling me that I need to edit ./docs/tutorial/index.rst ?

**Comment by marcharper** [comment]
Yes, the test output changed because of the updated mutation function, so the inline tests in the docs need to be updated.

**Review by marcharper — APPROVED** [review]

**Comment by drvinceknight** [comment]
So sorry I had completely missed this got opened and reviewed!

**Comment by drvinceknight** [comment]
Feel free to nudge me in the future :)

**Pull request merged**
