### PR TITLE
Move to opponents as player instances

### PR DESCRIPTION
**Pull request by drvinceknight**
I've changed things so we just pass players to the `Population` class. That class in it's init obtains the player classes and the init_kwargs.

I've also added a test with a few players that have caused pickling hurdles in the past.

I've tested locally and this works fine with the axelrod_fortran strategies.

### CODE REVIEW

**Comment by drvinceknight** [comment]
(I've been `squash and merge`ing the PRs I was opening to keep the history tidy)

**Comment by marcharper** [comment]
Cool. One issue to discuss: it looks like the kwarg args are a list, which suggests that if one wants to use them then empty dictionaries will have to be passed for other players. I think it would be better to pair them up somehow, by making opponents a list of tuples / namedtuples or having `opponent_init_kwargs` be a dictionary mapping indicies to kwargs.

**Comment by drvinceknight** [comment]
I'll change it to named tuples! 👍

**Comment by drvinceknight** [comment]
>  I think it would be better to pair them up somehow, by making opponents a list of tuples / namedtuples

Have paired these using a named tuple. ee8e3f1

Note that in practice a user won't need to create the `PlayerInfo`
tuples. These are constructed by the `Population.__init__` when it
deconstructs the player instances passed as the `opponents` variable (a
list).

**Pull request merged**
